name: hwspec

# Only run on branches (e.g. not tags)
on:
  workflow_dispatch:

jobs:
  spec:
    name: opensearch
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: ppc64le
            os: ubuntu-24.04-ppc64le
          - arch: s390x
            os: ubuntu-24.04-s390x
          - arch: amd64
            os: ubuntu-latest

    steps:
      - name: lscpu
        run: |
          # git config --global http.postBuffer 524288000
          git clone https://github.com/opensearch-project/opensearch.git
