name: hwspec

# Only run on branches (e.g. not tags)
on:
  workflow_dispatch:
  push:

jobs:
  spec:
    name: lscpu
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: ppc64le
            os: ubuntu-24.04-ppc64le
          - arch: s390x
            os: ubuntu-24.04-s390x
          - arch: amd64
            os: ubuntu-latest

    steps:
      - name: lscpu
        run: lscpu
