name: Z img pull

# Only run on branches (e.g. not tags)
on:
  workflow_dispatch:
  push:

jobs:
  fio:
    name: imgpull on ${{ matrix.arch }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: ppc64le
            os: ubuntu-24.04-ppc64le
          - arch: s390x
            os: ubuntu-24.04-s390x
          - arch: amd64
            os: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      # - name: Pull
      #   run: |

      #     docker pull quay.io/centos/centos:stream9
      #     docker pull registry.access.redhat.com/ubi9/ubi-minimal:latest

      #     docker image ls

      - name: RustUp
        run: |

          rustup --version
          file ruby 
          
